// Project-level store (global state)
import { create } from 'zustand'
import { persist } from 'zustand/middleware'
import type { ProjectState, AppSettings, UIState, NoteModifiers, SongMetadata } from '../types'
import { cloneDefaultHotkeys } from '../utils/hotkeys'
import { getSongStore } from './songStore'

interface ProjectStore extends ProjectState {
  // Actions
  setLoadedFolder: (path: string | null) => void
  addSong: (songId: string) => void
  removeSong: (songId: string) => void
  setActiveSong: (songId: string | null) => void
  clearProject: () => void
  loadFolder: (folderPath: string, selectSongId?: string) => Promise<void>
}

export const useProjectStore = create<ProjectStore>()((set) => ({
  // Initial state
  loadedFolderPath: null,
  songIds: [],
  activeSongId: null,

  // Actions
  setLoadedFolder: (path) =>
    set({ loadedFolderPath: path, songIds: [], activeSongId: null }),

  addSong: (songId) =>
    set((state) => ({
      songIds: state.songIds.includes(songId)
        ? state.songIds
        : [...state.songIds, songId]
    })),

  removeSong: (songId) =>
    set((state) => ({
      songIds: state.songIds.filter((id) => id !== songId),
      activeSongId: state.activeSongId === songId ? null : state.activeSongId
    })),

  setActiveSong: (songId) => set({ activeSongId: songId }),

  clearProject: () => set({ loadedFolderPath: null, songIds: [], activeSongId: null }),

  loadFolder: async (folderPath: string, selectSongId?: string) => {
    try {
      const songFolders = await window.api.scanFolder(folderPath)

      // Only clear state after we've confirmed the scan succeeded
      set({ loadedFolderPath: folderPath, songIds: [], activeSongId: null })

      for (const songFolder of songFolders) {
        try {
          const iniData = await window.api.readSongIni(songFolder.path)

          const metadata: SongMetadata = {
            ...(iniData ?? {}),
            name: (iniData?.name as string) || (iniData?.title as string) || songFolder.name,
            artist: (iniData?.artist as string) || 'Unknown Artist',
            album: iniData?.album as string,
            genre: iniData?.genre as string,
            year: iniData?.year !== undefined ? String(iniData.year) : undefined,
            charter: iniData?.charter as string,
            song_length: iniData?.song_length as number,
            preview_start_time: iniData?.preview_start_time as number
          }

          const store = getSongStore(songFolder.id)
          store.getState().loadSong({
            id: songFolder.id,
            folderPath: songFolder.path,
            metadata,
            notes: [],
            vocalNotes: [],
            vocalPhrases: [],
            starPowerPhrases: [],
            soloSections: [],
            laneMarkers: [],
            songSections: [],
            tempoEvents: [{ tick: 0, bpm: 120 }],
            timeSignatures: [{ tick: 0, numerator: 4, denominator: 4 }],
            videoSync: { clips: [], offsetMs: 0, trimStartMs: 0, trimEndMs: 0 },
            audioSync: { clips: [] },
            venueTrack: { autoGenerated: false, lighting: [], postProcessing: [], stage: [], performer: [], cameraCuts: [] },
            sourceFormat: 'midi'
          })

          set((state) => ({
            songIds: state.songIds.includes(songFolder.id)
              ? state.songIds
              : [...state.songIds, songFolder.id]
          }))
        } catch (error) {
          console.error(`Failed to load song ${songFolder.name}:`, error)
        }
      }

      if (songFolders.length > 0) {
        const targetId = selectSongId && songFolders.some((f) => f.id === selectSongId)
          ? selectSongId
          : songFolders[0].id
        set({ activeSongId: targetId })
      }
    } catch (error) {
      console.error('Error scanning folder:', error)
      const defaultPath = await window.api.getDefaultAutoChartOutputDir()
      if (folderPath !== defaultPath) {
        alert(
          `Error opening folder: ${error instanceof Error ? error.message : String(error)}\n\nFalling back to settings default folder: ${defaultPath}`
        )
        useSettingsStore.getState().updateSettings({ lastOpenedFolder: defaultPath })
        await useProjectStore.getState().loadFolder(defaultPath)
      } else {
        alert(`Error opening default folder: ${error instanceof Error ? error.message : String(error)}`)
      }
    }
  }
}))

// App settings store (persisted)
interface SettingsStore extends AppSettings {
  updateSettings: (settings: Partial<AppSettings>) => void
  resetSettings: () => void
}

const defaultSettings: AppSettings = {
  autosaveEnabled: true,
  autosaveIntervalMs: 2000,
  theme: 'dark',
  highwaySpeed: 1.0,
  audioLatencyMs: 0,
  volume: 0.8,
  pianoRollZoom: 2.0,
  snapDivision: 4,
  lastOpenedFolder: undefined,
  leftyFlip: false,
  waveformAudioSourcePath: undefined,
  enableAutoChart: true,
  autoChartOutputDir: undefined,
  sngLastExportDir: undefined,
  betaUpdates: false,
  invertPianoRollVerticalScroll: false,
  hotkeys: cloneDefaultHotkeys()
}

export const useSettingsStore = create<SettingsStore>()(
  persist(
    (set) => ({
      ...defaultSettings,

      updateSettings: (settings) => set((state) => ({ ...state, ...settings })),

      resetSettings: () => set(defaultSettings)
    }),
    {
      name: 'chart-editor-settings',
      merge: (persisted, current) => ({
        ...current,
        ...(persisted as Partial<SettingsStore>)
      })
    }
  )
)

// UI state store
interface UIStore extends UIState {
  setLeftPanelWidth: (width: number) => void
  setRightPanelWidth: (width: number) => void
  setBottomPanelHeight: (height: number) => void
  setBottomPanelTab: (tab: 'midi' | 'video') => void
  setSelectedVenueEvent: (event: UIState['selectedVenueEvent']) => void
  setFocusedPanel: (panel: UIState['focusedPanel']) => void
  setEditTool: (tool: UIState['editTool']) => void
  toggleModifier: (key: keyof NoteModifiers) => void
  clearModifiers: () => void
  togglePreviewFullscreen: () => void
  setSettingsModalOpen: (open: boolean) => void
  setExportModalOpen: (open: boolean) => void
  toggleVocalPitchPlayback: () => void
  toggleHighwayWaveform: () => void
}

const defaultModifiers: NoteModifiers = {
  cymbalOrTap: false,
  ghostOrHopo: false,
  accent: false,
  openOrKick: false,
  starPower: false,
  solo: false,
  talkie: false
}

export const useUIStore = create<UIStore>()((set) => ({
  // Initial state
  leftPanelWidth: 250,
  rightPanelWidth: 300,
  bottomPanelHeight: 200,
  bottomPanelTab: 'midi',
  selectedVenueEvent: null,
  focusedPanel: null,
  editTool: 'select',
  noteModifiers: { ...defaultModifiers },
  isPreviewFullscreen: false,
  isSettingsModalOpen: false,
  isExportModalOpen: false,
  vocalPitchPlayback: false,
  showHighwayWaveform: false,

  // Actions
  setLeftPanelWidth: (width) => set({ leftPanelWidth: width }),
  setRightPanelWidth: (width) => set({ rightPanelWidth: width }),
  setBottomPanelHeight: (height) => set({ bottomPanelHeight: height }),
  setBottomPanelTab: (tab) => set({ bottomPanelTab: tab }),
  setSelectedVenueEvent: (event) => set({ selectedVenueEvent: event }),
  setFocusedPanel: (panel) => set({ focusedPanel: panel }),
  setEditTool: (tool) => set({ editTool: tool }),
  toggleModifier: (key) =>
    set((state) => {
      const nextValue = !state.noteModifiers[key]
      if (!nextValue) {
        return {
          noteModifiers: { ...state.noteModifiers, [key]: false }
        }
      }

      return {
        noteModifiers: {
          cymbalOrTap: false,
          ghostOrHopo: false,
          accent: false,
          openOrKick: false,
          starPower: false,
          solo: false,
          talkie: false,
          [key]: true
        }
      }
    }),
  clearModifiers: () => set({ noteModifiers: { ...defaultModifiers } }),
  togglePreviewFullscreen: () => set((state) => ({ isPreviewFullscreen: !state.isPreviewFullscreen })),
  setSettingsModalOpen: (open) => set({ isSettingsModalOpen: open }),
  setExportModalOpen: (open) => set({ isExportModalOpen: open }),
  toggleVocalPitchPlayback: () => set((state) => ({ vocalPitchPlayback: !state.vocalPitchPlayback })),
  toggleHighwayWaveform: () => set((state) => ({ showHighwayWaveform: !state.showHighwayWaveform }))
}))
