export type StrumDevice = 'cuda' | 'mps' | 'cpu'

export type AutoChartStage =
  | 'bootstrap'
  | 'download'
  | 'separation'
  | 'drums'
  | 'guitar'
  | 'bass'
  | 'vocals'
  | 'keys'
  | 'merge'
  | 'complete'
  | 'error'

export interface AutoChartProgressEvent {
  runId: string
  stage: AutoChartStage
  message: string
  percent?: number
  currentItem?: string
}

export interface AutoChartRunOptions {
  runId: string
  cacheDir: string
  outputDir: string
  files: string[]
  folders: string[]
  /**
   * Pre-split stem folders. Each folder must contain individual stem files
   * (drums.wav, bass.wav, vocals.wav, other.wav) plus a song mix file
   * (song.wav / song.ogg / song.opus / song.mp3). The Python pipeline will
   * skip Demucs separation and use the user-supplied stems directly.
   */
  stemFolders: string[]
  /**
   * Per-instrument stem songs. Each entry yields one chart; values are
   * either local file paths or HTTP(S) URLs. Empty slots are skipped
   * (that instrument is not charted). The Demucs separation phase is
   * skipped entirely — the supplied stems are used as-is. The full mix
   * is always auto-generated by summing the supplied stems + extras.
   *
   * Vocal slots:
   *   - `vocals` — strictly lead vocals (charted as PART VOCALS).
   *   - `vocalsHarm2` — backing vocals 1, drives HARM2 and vocals_1.ogg.
   *   - `vocalsHarm3` — backing vocals 2, drives HARM3 and vocals_2.ogg.
   *
   * `extras` is a list of additional audio files/URLs that are NOT
   * charted. They are summed into the auto-mixed full mix and merged
   * into other.ogg so players hear them during playback.
   *
   * `crowd` is an optional single audio file exported directly as
   * crowd.ogg (CH/YARG play this as ambient crowd noise). Not included
   * in the analysis mix.
   */
  stemSongs?: Array<{
    name?: string
    stems: Partial<Record<'drums' | 'bass' | 'vocals' | 'other' | 'guitar' | 'piano' | 'vocalsHarm2' | 'vocalsHarm3' | 'crowd', string>>
    extras?: string[]
  }>
  urls: string[]
  includeKeys?: boolean
  /**
   * When true, skip all online metadata/album-art/lyric lookups in the
   * Python pipeline. Useful for fully-offline charting and to avoid
   * misidentifying custom uploads as well-known commercial songs.
   */
  disableOnlineLookup?: boolean
  /**
   * When true, skip vocal harmony detection (HARM2/HARM3 generation).
   * Saves a second whisper pass on the backing-vocals stem.
   */
  skipHarmonies?: boolean
  /**
   * Per-instrument enable flags. When omitted all tracks are charted.
   * `keys` here means standard 5-lane keys; pro-keys is currently always
   * generated alongside keys when enabled.
   */
  enabledTracks?: {
    drums?: boolean
    guitar?: boolean
    bass?: boolean
    vocals?: boolean
    harmonies?: boolean
    keys?: boolean
    proKeys?: boolean
  }
  /**
   * Optional user-supplied tempo map: a sorted (by `timeSec`) list of
   * tempo events. When provided, the first event's BPM overrides STRUM's
   * auto-detected initial tempo and the full list is written to the
   * resulting notes.mid; note ticks are retimed so real-world note
   * positions stay aligned with the audio.
   */
  tempoMap?: Array<{ timeSec: number; bpm: number }>
}

export interface AutoChartRunResult {
  success: boolean
  outputDir: string
  songFolders: string[]
  errors: string[]
  /**
   * Per-URL provenance: which URL input produced which song folder.
   * Only populated for `urls[]` entries; file/folder/stem inputs are not
   * listed. Used by the renderer to optionally download the source
   * video into the corresponding song folder after charting.
   */
  urlSongFolders?: Array<{ url: string; songFolder: string }>
}

